services:
    app:
        build: .
        container_name: notes_app
        restart: always
        ports:
            - '${PORT_APP}:3000'
        environment:
            DATABASE_NAME: ${DB_NAME}
            USERNAME_DB: ${DB_USERNAME}
            PASSWORD_DB: ${DB_PASSWORD}
            PORT_APP: ${PORT_APP}
        depends_on:
            - mongo

    mongo:
        image: mongo
        restart: always
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
            MONGO_INITDB_DATABASE: ${DB_NAME}
        volumes:
            - mongo-data:/var/lib/mongodb

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_SERVER: mongo
            ME_CONFIG_MONGODB_PORT: 27017
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USERNAME}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD}
            ME_CONFIG_MONGODB_URL: ${CONNECTION_URL_LOCAL}
            ME_CONFIG_BASICAUTH: 'true'

volumes:
    mongo-data:
